D2/final/miniflop/base/urls.py
from django.urls import path, re_path

from . import views

app_name = "base"

urlpatterns = [
    path('hello/', views.hello_world, name="hello"),
    re_path(r'^display/(?P<year>[0-9]{4})?',
         views.display,
         name="display"),
    path('fetch_scheduled_courses/<int:year>/',
         views.fetch_courses,
         name="fetch_courses"),
]

D2/final/miniflop/miniflop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('edt/', include('base.urls')),
]

D2/final/miniflop/base/models.py
from django.db import models

# Create your models here.

D2/final/miniflop/people/models.py
from django.db import models

# Create your models here.

D2/final/miniflop/base/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.staticfiles.views import serve

# Create your views here.
def hello_world(request):
    return HttpResponse("Salut !")


def display(request, year):
    if year is None:
        year = 0
        
    try:
        year = int(year)
    except ValueError:
        year = 0
        
    return render(request,
                  'base/edt.html',
                  {'yyyy': year})


def fetch_courses(request, year):

    if year not in [2018, 2019]:
        return serve(request,
                     'base/data.csv')

    return serve(request,
                 'base/data' + str(year) + '.csv')

D2/final/miniflop/people/views.py
from django.shortcuts import render

# Create your views here.

D2/final/miniflop/base/templates/base/edt.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<meta charset="utf-8"/>
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'base/style.css' %}" />
  <script src="{% static 'base/d3.v4.min.js' %}"></script>
  <script src="{% static 'base/jquery.min.js' %}"></script>
  <title>Client side : from csv to svg</title>
</head>
<h1>Un emploi du temps</h1>
<svg height="440" width="400">
  <g class="courses-layer">
  </g>
  <g class="grid-layer">
  </g>
</svg>
<script>
  var year = {{ yyyy }} ;
  var url_data = "{% url 'base:fetch_courses' year=yyyy %}" ; 
</script>
<script type='text/javascript' src="{% static 'base/script.js' %}"></script>
</html>